sudo: false
language: node_js

git:
  depth: 10

node_js:
  - 6
  - 8
  - 10
  - 12
  
matrix:
  - include:
    - os: windows
    - os: linux

install:
  - npm install
  - npm install -g codecov

script:
  - npm run eslint
  - npm run cover

after_script:
  - codecov
