language: node_js
sudo: false

git:
  depth: 10

node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm install
  - npm install -g codecov

script:
  - npm run eslint
  - npm run cover

after_script:
  - codecov
