sudo: false
language: node_js
node_js: 12

git:
  depth: 10

matrix:
  - include:
    - os: windows
    - os: linux

install:
  - npm install
  - npm install -g codecov

script:
  - npm run eslint
  - npm run cover

after_script:
  - codecov
