sudo: false
language: node_js
node_js: 12

git:
  depth: 10

os: 
  - linux
  - windows

install:
  - npm install
  - npm install -g codecov

script:
  - npm run eslint
  - npm run cover

after_script:
  - codecov
