sudo: false
language: node_js
node_js: 12

git:
  depth: 10

os: 
  - linux
  - windows

install:
  - npm install
  - npm install -g codecov
  - node --version
  - npm --version
  #- msbuild -version -nologo # no global msbuild on Travis it seems
  #- where msbuild # no where as well it seems
  - export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/Installer/"
  - export MSVC=$(vswhere -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath)
  - export MSVC=$(echo /$MSVC | sed -e 's/\\/\//g' -e 's/://')
  - export PATH="$PATH:$MSVC/MSBuild/15.0/Bin/"
  - echo $PATH

before_script:
  - dir template # where are we?
  - yes "" | certutil -user -importpfx templateCordovaApp_TemporaryKey.pfx

script:
  - npm run eslint
  - npm test

after_script:
  - codecov
